-- Weekly registration access code gate
-- Run inside Supabase SQL editor prior to enabling the edge function schedule

CREATE TABLE IF NOT EXISTS public.registration_access_codes (
  id BIGSERIAL PRIMARY KEY,
  code TEXT NOT NULL,
  valid_from TIMESTAMPTZ NOT NULL,
  valid_to TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.registration_access_codes IS 'Weekly rotating code used to authorize self-service registrations.';
COMMENT ON COLUMN public.registration_access_codes.code IS 'Human friendly access code generated by Supabase Edge function.';
COMMENT ON COLUMN public.registration_access_codes.valid_from IS 'Timestamp (UTC) marking the beginning of the code window.';
COMMENT ON COLUMN public.registration_access_codes.valid_to IS 'Timestamp (UTC) marking the expiration of the code window.';

ALTER TABLE public.registration_access_codes ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS registration_access_codes_valid_from_key
  ON public.registration_access_codes (valid_from);

CREATE INDEX IF NOT EXISTS registration_access_codes_window_idx
  ON public.registration_access_codes (valid_from DESC, valid_to DESC);

-- Example seed code to verify the workflow end-to-end in lower environments.
-- Replace the timestamp window and code as needed before executing in production.
INSERT INTO public.registration_access_codes (code, valid_from, valid_to)
VALUES (
  'PURVITA-ACCESS-2025-W01',
  TIMESTAMPTZ '2025-01-13 00:00:00+00',
  TIMESTAMPTZ '2025-01-20 00:00:00+00'
)
ON CONFLICT (valid_from) DO NOTHING;
